# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.PositiveIntegerField(choices=[(1, 'DOCUBE'), (2, 'JIFFY')], default=2)),
                ('sub_team', models.PositiveIntegerField(choices=[(1, 'ENGINEERING'), (2, 'QA'), (3, 'IMPLEMENTATION'), (4, 'ADMINISTRATION')], default=1)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(default='team_members/None/no-img.jpg', upload_to='team_members/')),
            ],
        ),
    ]
