# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='team/none/no-img.jpg', upload_to='team/members'),
        ),
    ]
