# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EciUser',
        ),
    ]
