# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0004_delete_eciuser'),
        ('relation', '0002_auto_20170804_0954'),
    ]

    operations = [
    ]
