# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0006_auto_20170817_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_join',
            field=models.CharField(default='This information is not available', max_length=100),
        ),
    ]
