# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0007_employee_date_of_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=1000)),
                ('date_of_upload', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='gallery/None/no-img.jpg', upload_to='gallery/')),
            ],
        ),
    ]
